export const userSites = [
  {
    communityProjectName: 'Alpha',
    siteName: 'San Francisco',
    siteId: '060731017',
    siteLatitude: '37.7749',
    siteLongitude: '-122.4194',
    siteElevation: '16.0',
    siteMonitors: [
      {
        monitorId: '939077866',
        monitorPurpose: 'Regulatory',
        monitorManufacturer: 'SensorCompany1',
        monitorModel: 'PA-II Dual Laser Air Sensor',
        monitorFirmwareVersion: '1490308331',
        monitorPurchaseDate: '12/20/2018',
        monitorLastServiceDate: '12/20/2018',
        monitorCfrCiting: 'Yes',
        monitorFlowRate: '2.5 L/min',
        monitorInletHeight: '2.85',
        monitorInletOrientation: '285',
        monitorInletDiameter: '0.25',
        monitorSystemDescription:
          'Using xyz software version (published 2002) for compatibility with our Windows 98 operating system /trailer on hill facing south.',
        monitorParameters: [
          {
            parameterCode: '81104',
            parameterName: 'PM 2.5',
            monitorMeasurementTechnique: '100511',
            monitorMeasurementUnits: '003',
            monitorSamplingDuration: '6',
            monitorSamplingFrequency: '80s',
            monitorUpperDetectionLimit: '10.3',
            monitorLowerDetectionLimit: '-5.25268',
            monitorMethodDetectionLimit: '0.00051',
            monitorDetectionRangeUnits: '003',
            monitorUncertainty: '±0.0067 μg/m³',
            monitorPrecision: '0.001 μg/m³',
            monitorMeasurementResolution: '1',
            monitorLastCalibrationTimestamp: '12/20/2018 14:02:26',
            dateStart: '12/20/2018',
          },
        ],
      },
      {
        monitorId: '219985723',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
    ],
  },
  {
    communityProjectName: 'Beta',
    siteName: 'Sacramento',
    siteId: '179859943',
    siteLatitude: '38.5816',
    siteLongitude: '-121.4944',
    siteElevation: '9.0',
    siteMonitors: [
      {
        monitorId: '406418863',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
    ],
  },
  {
    communityProjectName: 'Charlie',
    siteName: 'Los Angeles',
    siteId: '208163746',
    siteLatitude: '34.0522',
    siteLongitude: '-118.2437',
    siteElevation: '87.0',
    siteMonitors: [
      {
        monitorId: '490156703',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
      {
        monitorId: '553958860',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
      {
        monitorId: '709183220',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
    ],
  },
  {
    communityProjectName: 'Beta',
    siteName: 'Sacramento Zoo',
    siteId: '273730701',
    siteLatitude: '38.5396',
    siteLongitude: '-121.5038',
    siteElevation: '10.0',
    siteMonitors: [
      {
        monitorId: '274022374',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
      {
        monitorId: '748700923',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
    ],
  },
  {
    communityProjectName: 'Charlie',
    siteName: 'Los Angeles International Airport',
    siteId: '772864446',
    siteLatitude: '33.9416',
    siteLongitude: '-118.4085',
    siteElevation: '38.1',
    siteMonitors: [
      {
        monitorId: '235405440',
        monitorPurpose: null,
        monitorManufacturer: null,
        monitorModel: null,
        monitorFirmwareVersion: null,
        monitorPurchaseDate: null,
        monitorLastServiceDate: null,
        monitorCfrCiting: null,
        monitorFlowRate: null,
        monitorInletHeight: null,
        monitorInletOrientation: null,
        monitorInletDiameter: null,
        monitorSystemDescription: null,
        monitorParameters: [],
      },
    ],
  },
];
